services:
  bibliotecadigitalunifef-back:
    image: agenciatelabranca/bibliotecadigital-backend:latest
    container_name: bibliotecadigitalunifef-back
    networks:
      default:
        aliases:
          - db-central
      infra_network:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://atb-db-postgres:5432/db_biblioteca_digital_unifef
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postdba
      - MINIO_URL=http://atb-minio:9000
      - NEO4J_URI=bolt://atb-neo4j:7687
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8080 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 6
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bibliotecadigitalunifef-front:
    image: agenciatelabranca/bibliotecadigital-frontend:latest
    container_name: bibliotecadigitalunifef-front
    depends_on:
      bibliotecadigitalunifef-back:
        condition: service_healthy
    networks:
      default:
        aliases:
          - frontend
          - biblioteca-digital-unifef
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bibliotecadigitalunifef-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: bibliotecadigitalunifef-tunnel
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - default
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: biblioteca_digital_network
    external: true
  infra_network:
    external: true
    name: infra_default
