services:
  atb-minio:
    image: minio/minio
    container_name: atb-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - infra_default
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    volumes:
      - infra_minio_data:/data
    restart: always

  atb-neo4j:
    image: neo4j:latest
    container_name: atb-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - infra_default
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - infra_neo4j_data:/data
      - infra_neo4j_logs:/logs
    restart: always

networks:
  infra_default:
    external: true

volumes:
  infra_minio_data:
    external: true
  infra_neo4j_data:
    external: true
  infra_neo4j_logs:
    external: true
