services:
  back-biblioteca-digital:
    image: agenciatelabranca/bibliotecadigital-backend:latest
    container_name: back-biblioteca-digital
    networks:
      - default
      - infra_network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://atb-db-postgres:5432/db_biblioteca_digital_unifef
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postdba
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8080 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 6
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  biblioteca-digital-unifef:
    image: agenciatelabranca/bibliotecadigital-frontend:latest
    container_name: biblioteca-digital-unifef
    depends_on:
      back-biblioteca-digital:
        condition: service_healthy
    networks:
      - default
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  tunnel_biblioteca_digital_unifef:
    image: cloudflare/cloudflared:latest
    container_name: tunnel_biblioteca_digital_unifef
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - default
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  infra_network:
    external: true
    name: infra_default
