# Nome da aplicação
spring.application.name=db_biblioteca_digital_unifef
spring.profiles.active=dev

# Configurações do servidor
server.port=8080

# Compression (Gzip) - Espelhado do PDV
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
server.compression.min-response-size=1024

# Logs
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG

# JWT Padrão (dev)
jwt.secret=7468576D5A7134743777217A25432A46294A404E635266556A586E3272357538125
jwt.expiration=180000000

