# Nome da aplicação
spring.application.name=db_biblioteca_digital_unifef
spring.profiles.active=dev

# =========================================
# SpringDoc OpenAPI / Swagger
# =========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# =========================================
# Configurações do servidor
# =========================================
server.port=8080

# Compression (Gzip)
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
server.compression.min-response-size=2048


# =========================================
# Versão da aplicação (substituída pelo Maven)
# =========================================

jwt.secret=7468576D5A7134743777217A25432A46294A404E635266556A586E3272357538125
jwt.expiration=180000000
